version: "3"

services:

  mysql-conta:
    image: mysql:5.7.21
    volumes:
      - mysql-conta:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-conta

  mysql-pessoa:
    image: mysql:5.7.21
    volumes:
      - mysql-pessoa:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fe-pessoa

  conta:
    image: fernandoe/fe-conta-server:local
    ports:
      - "9000:8000"
    environment:
       DATABASE_URL: mysql://root:password@mysql-conta:3306/fe-conta
    depends_on:
      - mysql-conta

  pessoa:
    image: fernandoe/fe-pessoa-server:local
    ports:
      - "9001:8000"
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: 'mysql://root:password@mysql-pessoa:3306/fe-pessoa'
    depends_on:
      - mysql-pessoa

  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql-conta:
    external:
      name: mysql-conta
  mysql-pessoa:
    external:
      name: mysql-pessoa


networks:
  default:
    external:
      name: fe
